{% set version = "1.4.0" %}
{% set sha256 = "cb7a830d216e433518aeca389def4260940823308816358a5fc5d3beef682055" %}
{% set pip_name = 'xxhash' %}
{% set name = 'python-xxhash' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - msinttypes  # [win and py<35]
    - pip
  run:
    - python

test:
  imports:
    - xxhash
  commands:
    - conda inspect linkages {{ name|lower }}  # [unix]
    - conda inspect objects {{ name|lower }}   # [osx]

about:
  home: https://github.com/ifduyue/python-xxhash
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Python binding for xxHash'
  license_family: BSD

extra:
  recipe-maintainers:
    - mariusvniekerk
