{% set version = "2.0.0" %}
{% set sha256 = "58ca818554c1476fa1456f6cd4b87002e2294f09baf0f81e5a2a4968e62c423c" %}
{% set pip_name = "xxhash" %}
{% set name = "python-xxhash" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz

build:
  number: 2
  script:
    - export XXHASH_LINK_SO=1  # [unix]
    - SET XXHASH_LINK_SO=1  # [win]
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - msinttypes  # [win and py<35]
    - pip
    - xxhash
  run:
    - python
    - xxhash

test:
  imports:
    - xxhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ifduyue/python-xxhash
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python binding for xxHash
  license_family: BSD

extra:
  recipe-maintainers:
    - mariusvniekerk
